# Permalinks
permalink:           pretty
relative_permalinks: false

# Setup
title:               Chris McCormick
tagline:             Machine Learning Tutorials and Insights
url:                 http://getpoole.com
paginate:            1
baseurl:             http://chrisjmccormick.github.io/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Chris McCormick
  url:               https://twitter.com/chrisjmccormick
  email:             chrisjmccormick@in2h2.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/chrisjmccormick/chrisjmccormick.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
