# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true   # Had to remove this for Jekyll 3.0...

# Setup
title:               Chris McCormick
tagline:             Machine Learning Tutorials and Insights
url:                 mccormickml.com
paginate:            1
baseurl:             http://chrisjmccormick.github.io/mccormickml/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Chris McCormick
  url:               https://twitter.com/chrisjmccormick
  email:             chrisjmccormick@in2h2.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/chrisjmccormick/mccormickml
